version: '3.7'
services:
  postgres:
    image: postgres:12.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: "200k"
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./docker-entrypoint/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
